### PR TITLE
actix_web 4 support

### PR DESCRIPTION
**Pull request by AOx0**
**Changes:**
- Actix Web v4+ support (all dependencies upgraded)
- Rust edition upgrade to 2021
- Version strings within README.md updated
- Included @tglman's #3

### CODE REVIEW

**Comment by marknijboer** [comment]
It might be a good idea to pin the actix-web version in cargo.toml to `4` instead of a specific major/minor/patch as currently: `4.0.0-beta.19`. This will allow this package to use a version of the actix-web dependency from other packages/dependencies

**Comment by AOx0** [comment]
Did not notice actix v4 was released :o

**Comment by Mohan6677** [comment]
When will this branch be merged?

**Comment by sylv256** [comment]
really need this
i think the author abandoned us

**Pull request closed without merging**
